package com.example.ui.components

import com.example.ui.viewmodel.AppLanguage

object LanguageResources {
    private val strings = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "UniConvert",
            "offline_status" to "Offline Local Database Active",
            "converter" to "Converter",
            "history" to "History",
            "customize" to "Customize",
            "control" to "Control",
            "select_category" to "Select Category",
            "no_categories" to "No active unit types. Go to Customize to enable them!",
            "from" to "From",
            "to" to "To",
            "copy" to "Copy",
            "save_log" to "Save Log",
            "rule_title" to "Conversion Rule",
            "rule_desc" to "Conversion uses the offline base standard. 1 %s is %s %s.",
            "copied_toast" to "Copied %s %s to clipboard",
            "logged_toast" to "Conversion logged offline",
            "search_placeholder" to "Search unit...",
            "no_units" to "No units found",
            "cancel" to "Cancel",
            "history_title" to "Conversion History Logs",
            "clear_all_confirm" to "Clear All Logs?",
            "clear_all_desc" to "This will permanently delete all offline historical logs. This action is irreversible.",
            "delete_all_btn" to "Delete Everything",
            "history_empty_title" to "Your offline database is clear.",
            "history_empty_desc" to "Any calculations you perform in the calculator can be logged here for offline reference.",
            "delete_log" to "Delete this conversion log",
            "active_unit_types" to "Active Unit Types",
            "category_toggle_desc" to "Toggle which categories show up on home.",
            "custom_badge" to "Custom",
            "delete_custom_cat" to "Tap delete to remove permanently",
            "customize_multipliers" to "Customize Multipliers & Units",
            "customize_desc" to "Review conversions and add custom multiplier units.",
            "add_custom_unit" to "Add Custom Unit",
            "factor_base" to "Factor base: %s, Offset: %s",
            "add_category_title" to "Add Custom Category",
            "category_name_placeholder" to "Category Name (e.g. Speed)",
            "select_category_icon" to "Select Category Icon",
            "create" to "Create",
            "add_unit_title" to "Add custom unit to %s",
            "unit_name_placeholder" to "Unit Name (e.g. Nanometer)",
            "symbol_placeholder" to "Symbol (e.g. nm)",
            "multiplier_label" to "Multiplier to base (decimal factor)",
            "offset_label" to "Additive Offset (if any)",
            "calc_rule_note" to "Calculation rule: Offset is subtracted from raw custom value and then multiplied by Factor to convert to base metric standard.",
            "control_title" to "Control & Prefs",
            "theme_mode" to "App Visual Theme",
            "theme_system" to "System Default",
            "theme_light" to "Force Light",
            "theme_dark" to "Force Dark",
            "app_lang" to "App Translation",
            "about_app" to "About UniConvert",
            "about_desc" to "UniConvert is a state-of-the-art offline unit conversion engine designed with precision in mind. Built on modern MVVM architecture, it offers full SQLite Room support to store your calculations and customize categories easily.",
            "developer" to "Developer Information",
            "dev_name" to "Lead Developer: AI Studio Builder",
            "dev_contact" to "Contact: lead@uniconvert.local",
            "privacy_policy" to "Privacy Policy",
            "privacy_desc" to "Your data is 100% yours. UniConvert stores all data (settings, custom units, custom categories, and history logs) completely offline. We do not transmit or collect telemetry data.",
            "version" to "Application Version",
            "version_val" to "v1.1.0 (Production Stable)"
        ),
        AppLanguage.SPANISH to mapOf(
            "app_title" to "UniConvert",
            "offline_status" to "Base de datos local fuera de línea activa",
            "converter" to "Convertidor",
            "history" to "Historial",
            "customize" to "Personalizar",
            "control" to "Control",
            "select_category" to "Seleccionar Categoría",
            "no_categories" to "No hay tipos de unidades activadas. ¡Vaya a Personalizar para activarlas!",
            "from" to "Desde",
            "to" to "A",
            "copy" to "Copiar",
            "save_log" to "Guardar registro",
            "rule_title" to "Regla de Conversión",
            "rule_desc" to "La conversión utiliza el estándar base fuera de línea. 1 %s es %s %s.",
            "copied_toast" to "Copiado %s %s al portapapeles",
            "logged_toast" to "Conversión registrada fuera de línea",
            "search_placeholder" to "Buscar unidad...",
            "no_units" to "No se encontraron unidades",
            "cancel" to "Cancelar",
            "history_title" to "Historial de Conversiones",
            "clear_all_confirm" to "¿Limpiar todos los registros?",
            "clear_all_desc" to "Esto borrará permanentemente todo el historial fuera de línea. Esta acción es irreversible.",
            "delete_all_btn" to "Eliminar Todo",
            "history_empty_title" to "Su base de datos está limpia.",
            "history_empty_desc" to "Cualquier cálculo que realice en la calculadora puede registrarse aquí para referencia fuera de línea.",
            "delete_log" to "Eliminar este registro de conversión",
            "active_unit_types" to "Tipos de Unidades Activos",
            "category_toggle_desc" to "Alterna qué categorías se muestran en el inicio.",
            "custom_badge" to "Personalizado",
            "delete_custom_cat" to "Toque eliminar para borrar permanentemente",
            "customize_multipliers" to "Personalizar multiplicadores y unidades",
            "customize_desc" to "Revise las conversiones y agregue factores personalizados.",
            "add_custom_unit" to "Agregar Unidad Personalizada",
            "factor_base" to "Factor base: %s, Compensado: %s",
            "add_category_title" to "Agregar Categoría Personalizada",
            "category_name_placeholder" to "Nombre de categoría (ej. Velocidad)",
            "select_category_icon" to "Seleccionar icono de categoría",
            "create" to "Crear",
            "add_unit_title" to "Agregar unidad personalizada a %s",
            "unit_name_placeholder" to "Nombre de unidad (ej. Nanómetro)",
            "symbol_placeholder" to "Símbolo (ej. nm)",
            "multiplier_label" to "Multiplicador a base (factor decimal)",
            "offset_label" to "Compensación aditiva (si existe)",
            "calc_rule_note" to "Regla: La compensación se resta de la unidad personalizada y se multiplica por el factor para convertir al estándar base.",
            "control_title" to "Control y Ajustes",
            "theme_mode" to "Tema Visual de la App",
            "theme_system" to "Predeterminado del Sistema",
            "theme_light" to "Forzar Modo Claro",
            "theme_dark" to "Forzar Modo Oscuro",
            "app_lang" to "Traducción de la App",
            "about_app" to "Acerca de UniConvert",
            "about_desc" to "UniConvert es un motor de conversión confiable desarrollado con precisión absoluta. Ofrece almacenamiento SQLite Room local para guardar sus conversiones de forma segura y privada.",
            "developer" to "Información del Desarrollador",
            "dev_name" to "Desarrollador principal: AI Studio Builder",
            "dev_contact" to "Contacto: lead@uniconvert.local",
            "privacy_policy" to "Política de Privacidad",
            "privacy_desc" to "Sus datos le pertenecen al 100%. UniConvert guarda toda la información localmente en su dispositivo y no transmite telemetría externa.",
            "version" to "Versión de la Aplicación",
            "version_val" to "v1.1.0 (Producción Estable)"
        ),
        AppLanguage.FRENCH to mapOf(
            "app_title" to "UniConvert",
            "offline_status" to "Base de données locale hors ligne active",
            "converter" to "Convertisseur",
            "history" to "Historique",
            "customize" to "Personnaliser",
            "control" to "Contrôle",
            "select_category" to "Sélectionner la catégorie",
            "no_categories" to "Aucun type d'unité activé. Allez dans Personnaliser pour les activer !",
            "from" to "De",
            "to" to "À",
            "copy" to "Copier",
            "save_log" to "Enregistrer",
            "rule_title" to "Règle de conversion",
            "rule_desc" to "La conversion utilise le standard de base hors ligne. 1 %s vaut %s %s.",
            "copied_toast" to "Copié %s %s dans le presse-papiers",
            "logged_toast" to "Conversion enregistrée hors ligne",
            "search_placeholder" to "Rechercher une unité...",
            "no_units" to "Aucune unité trouvée",
            "cancel" to "Annuler",
            "history_title" to "Historique de conversion",
            "clear_all_confirm" to "Effacer tout l'historique ?",
            "clear_all_desc" to "Cela supprimera définitivement tous les journaux hors ligne. Cette action est irréversible.",
            "delete_all_btn" to "Tout supprimer",
            "history_empty_title" to "Votre base de données hors ligne est vide.",
            "history_empty_desc" to "Tous les calculs que vous effectuez peuvent être enregistrés ici pour référence hors ligne.",
            "delete_log" to "Supprimer ce journal de conversion",
            "active_unit_types" to "Types d'unités actifs",
            "category_toggle_desc" to "Choisissez les catégories à afficher à l'accueil.",
            "custom_badge" to "Personnalisé",
            "delete_custom_cat" to "Appuyez sur supprimer pour effacer définitivement",
            "customize_multipliers" to "Personnaliser les multiplicateurs & unités",
            "customize_desc" to "Vérifiez les conversions et ajoutez des facteurs personnalisés.",
            "add_custom_unit" to "Ajouter une unité personnalisée",
            "factor_base" to "Facteur de base : %s, Décalage : %s",
            "add_category_title" to "Ajouter une catégorie personnalisée",
            "category_name_placeholder" to "Nom de la catégorie (ex. Vitesse)",
            "select_category_icon" to "Sélectionner l'icône de catégorie",
            "create" to "Créer",
            "add_unit_title" to "Ajouter une unité personnalisée à %s",
            "unit_name_placeholder" to "Nom de l'unité (ex. Nanomètre)",
            "symbol_placeholder" to "Symbole (ex. nm)",
            "multiplier_label" to "Multiplicateur de base (facteur décimal)",
            "offset_label" to "Décalage additif (éventuel)",
            "calc_rule_note" to "Règle : Le décalage est soustrait puis multiplié par le facteur pour obtenir l'unité de base.",
            "control_title" to "Contrôle & Ajustements",
            "theme_mode" to "Thème Visuel de l'App",
            "theme_system" to "Thème du Système",
            "theme_light" to "Mode Clair",
            "theme_dark" to "Mode Sombre",
            "app_lang" to "Langue de l'App",
            "about_app" to "À propos d'UniConvert",
            "about_desc" to "UniConvert est un moteur de conversion autonome hautement précis, conçu avec une architecture moderne Room & MVVM.",
            "developer" to "Développeur",
            "dev_name" to "Lead Développeur : AI Studio Builder",
            "dev_contact" to "Contact : lead@uniconvert.local",
            "privacy_policy" to "Politique de Confidentialité",
            "privacy_desc" to "Vos données vous appartiennent à 100%. UniConvert stocke tout localement hors ligne sans émettre de télémétrie.",
            "version" to "Version de l'application",
            "version_val" to "v1.1.0 (Fixe Stable)"
        ),
        AppLanguage.GERMAN to mapOf(
            "app_title" to "UniConvert",
            "offline_status" to "Lokale Offline-Datenbank aktiv",
            "converter" to "Konverter",
            "history" to "Verlauf",
            "customize" to "Anpassen",
            "control" to "Steuerung",
            "select_category" to "Kategorie auswählen",
            "no_categories" to "Keine aktiven Einheiten. Gehe zu Anpassen, um welche zu aktivieren!",
            "from" to "Von",
            "to" to "Nach",
            "copy" to "Kopieren",
            "save_log" to "Speichern",
            "rule_title" to "Berechnungsregel",
            "rule_desc" to "Verwendet den Offline-Standardwert. 1 %s ist %s %s.",
            "copied_toast" to "%s %s in Zwischenablage kopiert",
            "logged_toast" to "Ergebnis offline gespeichert",
            "search_placeholder" to "Einheit suchen...",
            "no_units" to "Keine Einheiten gefunden",
            "cancel" to "Abbrechen",
            "history_title" to "Verlaufsprotokolle",
            "clear_all_confirm" to "Verlauf leeren?",
            "clear_all_desc" to "Dies löscht dauerhaft alle Offline-Protokolle. Dieser Vorgang ist unumkehrbar.",
            "delete_all_btn" to "Alles Löschen",
            "history_empty_title" to "Ihr Protokollverlauf ist leer.",
            "history_empty_desc" to "Alle hier getätigten Umrechnungen können für Offline-Referenz gespeichert werden.",
            "delete_log" to "Dieses Protokoll löschen",
            "active_unit_types" to "Aktive Inhaltsbereiche",
            "category_toggle_desc" to "Wähle aus, welche Kategorien auf der Hauptseite erscheinen.",
            "custom_badge" to "Eigene",
            "delete_custom_cat" to "Klicke Löschen um permanent zu entfernen",
            "customize_multipliers" to "Multiplikatoren & Einheiten anpassen",
            "customize_desc" to "Überprüfe Umrechnungen und füge eigene Faktoren hinzu.",
            "add_custom_unit" to "Eigene Einheit hinzufügen",
            "factor_base" to "Grundfaktor: %s, Offset: %s",
            "add_category_title" to "Kategorie hinzufügen",
            "category_name_placeholder" to "Kategoriename (z.B. Geschwindigkeit)",
            "select_category_icon" to "Symbol auswählen",
            "create" to "Erstellen",
            "add_unit_title" to "Eigene Einheit zu %s hinzufügen",
            "unit_name_placeholder" to "Einheitenname (z.B. Nanometer)",
            "symbol_placeholder" to "Symbol (z.B. nm)",
            "multiplier_label" to "Multiplikator zu Basiswert",
            "offset_label" to "Offset-Korrektur (falls vorhanden)",
            "calc_rule_note" to "Regel: Der Offset wird vom Rohwert abgezogen und dann für den Basiswert multipliziert.",
            "control_title" to "Optionen & Steuerung",
            "theme_mode" to "Visuelles Farbthema",
            "theme_system" to "Systemvoreinstellung",
            "theme_light" to "Helles Thema",
            "theme_dark" to "Dunkles Thema",
            "app_lang" to "App-Sprache",
            "about_app" to "Über UniConvert",
            "about_desc" to "UniConvert ist ein präziser, moderner Offline-Einheitenkonverter auf Basis von Room & MVVM.",
            "developer" to "Entwicklerinformationen",
            "dev_name" to "Lead Entwickler: AI Studio Builder",
            "dev_contact" to "Kontakt: lead@uniconvert.local",
            "privacy_policy" to "Datenschutzerklärung",
            "privacy_desc" to "Ihre Daten gehören zu 100% Ihnen. Alle Verlaufsdaten und Einstellungen verbleiben komplett lokal auf Ihrem Gerät.",
            "version" to "Anwendungsversion",
            "version_val" to "v1.1.0 (Produktion Stabil)"
        ),
        AppLanguage.BANGLA to mapOf(
            "app_title" to "UniConvert",
            "offline_status" to "অফলাইন লোকাল ডাটাবেস সক্রিয়",
            "converter" to "রূপান্তরকারী",
            "history" to "ইতিহাস",
            "customize" to "কাস্টমাইজ",
            "control" to "নিয়ন্ত্রণ",
            "select_category" to "ক্যাটাগরি নির্বাচন করুন",
            "no_categories" to "কোনো সক্রিয় ইউনিট টাইপ নেই। চালু করতে কাস্টমাইজে যান!",
            "from" to "থেকে",
            "to" to "প্রতি",
            "copy" to "অনুলিপি",
            "save_log" to "লগ সংরক্ষণ করুন",
            "rule_title" to "রূপান্তরের নিয়ম",
            "rule_desc" to "রূপান্তর অফলাইন বেস মান ব্যবহার করে। ১ %s হলো %s %s।",
            "copied_toast" to "ক্লিপবোর্ডে %s %s অনুলিপি করা হয়েছে",
            "logged_toast" to "রূপান্তরটি অফলাইনে লগ করা হয়েছে",
            "search_placeholder" to "ইউনিট খুঁজুন...",
            "no_units" to "কোনো ইউনিট পাওয়া যায়নি",
            "cancel" to "বাতিল",
            "history_title" to "রূপান্তর ইতিহাসের লগসমূহ",
            "clear_all_confirm" to "সব লগ মুছে ফেলবেন?",
            "clear_all_desc" to "এটি চিরতরে সমস্ত অফলাইন ইতিহাস মুছে ফেলবে। এই কাজটি পরিবর্তন করা যাবে না।",
            "delete_all_btn" to "সবকিছু মুছে ফেলুন",
            "history_empty_title" to "আপনার অফলাইন ডাটাবেস খালি আছে।",
            "history_empty_desc" to "অফলাইন রেফারেন্সের জন্য আপনার হিসাবগুলো এখানে সংরক্ষণ করতে পারেন।",
            "delete_log" to "এই রূপান্তর লগটি মুছে দিন",
            "active_unit_types" to "সক্রিয় ইউনিটের প্রকারভেদ",
            "category_toggle_desc" to "হোম স্ক্রিনে কোন ক্যাটাগরিগুলো দেখাবে তা টগল করুন।",
            "custom_badge" to "কাস্টম",
            "delete_custom_cat" to "স্থায়ীভাবে মুছে ফেলতে ডিলিট চাপুন",
            "customize_multipliers" to "গুণক এবং ইউনিট কাস্টমাইজ করুন",
            "customize_desc" to "রূপান্তর পর্যালোচনা করুন এবং নতুন কাস্টম গুণক ইউনিট যোগ করুন।",
            "add_custom_unit" to "কাস্টম ইউনিট যোগ করুন",
            "factor_base" to "বেস ফ্যাক্টর: %s, অফসেট: %s",
            "add_category_title" to "কাস্টম ক্যাটাগরি যোগ করুন",
            "category_name_placeholder" to "ক্যাটাগরির নাম (যেমন: গতি)",
            "select_category_icon" to "ক্যাটাগরি আইকন নির্বাচন করুন",
            "create" to "তৈরি করুন",
            "add_unit_title" to "%s-তে কাস্টম ইউনিট যোগ করুন",
            "unit_name_placeholder" to "ইউনিটের নাম (যেমন: ন্যানোমিটার)",
            "symbol_placeholder" to "প্রতীক (যেমন: nm)",
            "multiplier_label" to "বেস গুণক (দশমিক মান)",
            "offset_label" to "অ্যাডিটিভ অফসেট (যদি থাকে)",
            "calc_rule_note" to "হিসাবের নিয়ম: কাস্টম মান থেকে অফসেট বিয়োগ করা হবে এবং তারপর বেস মেট্রিকে রূপান্তর করতে গুণক দিয়ে গুণ করা হবে।",
            "control_title" to "নিয়ন্ত্রণ ও সেটিংস",
            "theme_mode" to "অ্যাপের থিম",
            "theme_system" to "সিস্টেম ডিফল্ট",
            "theme_light" to "লাইট মোড",
            "theme_dark" to "ডার্ক মোড",
            "app_lang" to "অ্যাপের ভাষা",
            "about_app" to "UniConvert সম্পর্কে",
            "about_desc" to "UniConvert হলো একটি নির্ভুল অফলাইন ইউনিট রূপান্তরকারী ইঞ্জিন। আধুনিক MVVM আর্কিটেকচার এবং SQLite Room-এর সাহায্যে এটি আপনার সমস্ত হিসাব ও ক্যাটাগরি সম্পূর্ণ নিরাপদে অফলাইনে সংরক্ষণ করে।",
            "developer" to "ডেভেলপার তথ্য",
            "dev_name" to "প্রধান ডেভেলপার: এআই স্টুডিও বিল্ডার",
            "dev_contact" to "যোগাযোগ: lead@uniconvert.local",
            "privacy_policy" to "গোপনীয়তা নীতি",
            "privacy_desc" to "আপনার ডাটা ১০০% আপনারই। UniConvert সমস্ত সেটিংস, কাস্টম ইউনিট, কাস্টম ক্যাটাগরি এবং রূপান্তর লগ সম্পূর্ণ অফলাইনে সংরক্ষণ করে। আমরা কোনো তথ্য সংগ্রহ বা প্রেরণ করি না।",
            "version" to "অ্যাপ্লিকেশন সংস্করণ",
            "version_val" to "v1.1.0 (স্থিতিশীল সংস্করণ)"
        )
    )

    fun getString(language: AppLanguage, key: String): String {
        return strings[language]?.get(key) ?: strings[AppLanguage.ENGLISH]?.get(key) ?: ""
    }
}
